<a href="https://colab.research.google.com/github/MelchiorKaczmarzyk/InternshipTutorialCode/blob/main/Internship_excercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Hello Collab!

In [987]:
print("Hello Collab!")

Hello Collab!


###Import libraries

In [988]:
import numpy as np
import pandas as pd
import sklearn

### Data generating

In [989]:
data = {
    "size": ["XL", "L", "M", "L", "M"],
    "color": ["red", "green", "blue", "green", "red"],
    "gender": ["female", "male", "male", "female", "female"],
    "price": [199.0, 89.0, 99.0, 129.0, 79.0],
    "weight": [500, 450, 300, 380, 410],
    "bought": ["yes", "no", "yes", "no", "yes"]
}

#Utworzenie z obiektu DataFrame na podstawie wyżej zdafiniowanego obiektu
df_raw = pd.DataFrame(data = data)
df_raw

size  color  gender  price  weight bought
0   XL    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     380     no
4    M    red  female   79.0     410    yes

###Create a copy and describe the dataframe

In [990]:
df = df_raw.copy()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   size    5 non-null      object 
 1   color   5 non-null      object 
 2   gender  5 non-null      object 
 3   price   5 non-null      float64
 4   weight  5 non-null      int64  
 5   bought  5 non-null      object 
dtypes: float64(1), int64(1), object(4)
memory usage: 368.0+ bytes


###Changing some of the object-type data to categorical data

In [991]:
# Categorical data allow for easier visualisations
for col in ["size", "color", "gender", "bought"]:
  df[col] = df[col].astype("category")
df["weight"] = df["weight"].astype("float")

# Only shows data for columns with numeric values
df.describe()
df.describe(include=['category'])

size  color  gender bought
count     5      5       5      5
unique    3      3       2      2
top       L  green  female    yes
freq      2      2       3      3

###Using LabelEncoder




In [992]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
#le.fit(df['bought'])
#le.transform(df['bought'])
#le.fit_transform(df['bought']) executes fit and then transform
#You were doing that with mushrooms too so you could use one-hot encoding!
df['bought'] = le.fit_transform(df['bought'])
df

size  color  gender  price  weight  bought
0   XL    red  female  199.0   500.0       1
1    L  green    male   89.0   450.0       0
2    M   blue    male   99.0   300.0       1
3    L  green  female  129.0   380.0       0
4    M    red  female   79.0   410.0       1

###Possible transform inversion

In [993]:
# LabelEncoder should be only used for target data
df['bought'] = le.inverse_transform(df['bought'])
df

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue    male   99.0   300.0    yes
3    L  green  female  129.0   380.0     no
4    M    red  female   79.0   410.0    yes

OneHotEncoder

In [994]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(sparse_output=False)
encoder.fit_transform(df[['size']])
# In the output 1 indicates L in the first column, M in the second and XL in the third

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [995]:
encoder.categories_

[array(['L', 'M', 'XL'], dtype=object)]

In [996]:
encoder = OneHotEncoder(drop='first', sparse_output=False)
encoder.fit_transform(df[['size']])
#First column has been dropped as it is redundant : zeroes in both columns in a given row indicaste the third value

array([[0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.]])

In [997]:
#I don't think the output makes sense...
df_new_copy = df.copy()
df_new_copy['size'] = encoder.fit_transform(df[['size']])
df_new_copy
#... but we will be using get_dummies instead!

size  color  gender  price  weight bought
0   0.0    red  female  199.0   500.0    yes
1   0.0  green    male   89.0   450.0     no
2   1.0   blue    male   99.0   300.0    yes
3   0.0  green  female  129.0   380.0     no
4   1.0    red  female   79.0   410.0    yes

###Using pandas get_dummies

In [998]:
# It's used INSTEAD OF OneHotEncoder
pd.get_dummies(data=df)

price  weight  size_L  size_M  size_XL  color_blue  color_green  color_red  \
0  199.0   500.0   False   False     True       False        False       True   
1   89.0   450.0    True   False    False       False         True      False   
2   99.0   300.0   False    True    False        True        False      False   
3  129.0   380.0    True   False    False       False         True      False   
4   79.0   410.0   False    True    False       False        False       True   

   gender_female  gender_male  bought_no  bought_yes  
0           True        False      False        True  
1          False         True       True       False  
2          False         True      False        True  
3           True        False       True       False  
4           True        False      False        True

In [999]:
#Remove redundant columns as before
pd.get_dummies(data=df, drop_first=True)

price  weight  size_M  size_XL  color_green  color_red  gender_male  \
0  199.0   500.0   False     True        False       True        False   
1   89.0   450.0   False    False         True      False         True   
2   99.0   300.0    True    False        False      False         True   
3  129.0   380.0   False    False         True      False        False   
4   79.0   410.0    True    False        False       True        False   

   bought_yes  
0        True  
1       False  
2        True  
3       False  
4        True

In [1000]:
# You can change the separator
pd.get_dummies(data=df, drop_first=True, prefix_sep='-')
# You can also choose only selected columns to be affected using cols parameter

price  weight  size-M  size-XL  color-green  color-red  gender-male  \
0  199.0   500.0   False     True        False       True        False   
1   89.0   450.0   False    False         True      False         True   
2   99.0   300.0    True    False        False      False         True   
3  129.0   380.0   False    False         True      False        False   
4   79.0   410.0    True    False        False       True        False   

   bought-yes  
0        True  
1       False  
2        True  
3       False  
4        True

###Standardization

In [1001]:
# W pandas jest obciążony estymator wariancji, w numpy nieobciążony, więc dawać niezgodne wyniki

# Printing an array
print(f"{df['price']}\n")

print(f"Mean: {df['price'].mean()}" )
# That's a weird syntax...
print(f"Standard deviation: {df['price'].std():.4f}" )

0    199.0
1     89.0
2     99.0
3    129.0
4     79.0
Name: price, dtype: float64

Mean: 119.0
Standard deviation: 48.4768


In [1002]:
# Array arithmetic is so easy in Python!
(df['price'] - df['price'].mean()) / df['price'].std()

0    1.650274
1   -0.618853
2   -0.412568
3    0.206284
4   -0.825137
Name: price, dtype: float64

In [1003]:
# Function solution
def standadize(x):
  return (x - x.mean()) / x.std()

In [1004]:
# Using imported function from sklearn
from sklearn.preprocessing import scale
scale(df['price'])
# Note that the result is somewhat different

array([ 1.84506242, -0.69189841, -0.4612656 ,  0.2306328 , -0.92253121])

In [1005]:
#Best solution : imported StandardScaler class
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df[['price', 'weight']] = scaler.fit_transform(df[['price', 'weight']])
df

size  color  gender     price    weight bought
0   XL    red  female  1.845062  1.366002    yes
1    L  green    male -0.691898  0.623610     no
2    M   blue    male -0.461266 -1.603567    yes
3    L  green  female  0.230633 -0.415740     no
4    M    red  female -0.922531  0.029696    yes

In [1006]:
df_raw

size  color  gender  price  weight bought
0   XL    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     380     no
4    M    red  female   79.0     410    yes

###Summary

In [1007]:
# Changing types
df_new = df_raw.copy()
for col in ["size", "color", "gender", "bought"]:
  df_new[col] = df_new[col].astype("category")
df_new["weight"] = df_new["weight"].astype("float")

# Encoding True as 1 and False as 0
le_new = LabelEncoder()
df_new['bought'] = le_new.fit_transform(df_new['bought'])

# Change categoricals to binary data with onehot encoding
df_new = pd.get_dummies(data=df_new, drop_first=True)

df_new[['size_M',	'size_XL',	'color_green',	'color_red', 'gender_male']] = df_new[['size_M',	'size_XL',	'color_green',	'color_red',	'gender_male']].apply(LabelEncoder().fit_transform)

# Standardization
scaler_new = StandardScaler()
df_new[['price', 'weight']] = scaler_new.fit_transform(df_new[['price', 'weight']])
df_new

price    weight  bought  size_M  size_XL  color_green  color_red  \
0  1.845062  1.366002       1       0        1            0          1   
1 -0.691898  0.623610       0       0        0            1          0   
2 -0.461266 -1.603567       1       1        0            0          0   
3  0.230633 -0.415740       0       0        0            1          0   
4 -0.922531  0.029696       1       1        0            0          1   

   gender_male  
0            0  
1            1  
2            1  
3            0  
4            0